### DISCUSSION TITLE
v1.0.5 and beyond may not be installable from Ansible Galaxy

### DISCUSSION THREAD

**Discussion by lae** [lae/ansible-role-netbox#174] [Announcements]
v1.0.5 is failing to be imported on the new Galaxy website due to a issue around cosmetics/difference between Galaxy and GitHub. For this and later versions, you can specify to install this role from GitHub in your `requirements.yml` as follows:

```yaml
---
- name: lae.netbox
  src: https://github.com/lae/ansible-role-netbox.git
  version: v1.0.5
```

For more information: https://forum.ansible.com/t/alternative-readme-paths-should-be-supported/4056
