### ISSUE TITLE
Permission error with version v1.0.0rc1

### ISSUE THREAD

**Issue by smutel** [lae/ansible-role-netbox#100]
Hello,

I installed netbox with the version 0.9.x of this playbook.  
I would like to switch to new version (v1.0.0rc1) of this playbook (to install new pip dependencies) without upgrading netbox.

When I execute the playbook again, I have this error:
```yaml
failed: [xxxxxx] (item=dns) => changed=false 
  ansible_loop_var: item
  attempts: 2
  cmd:
  - /opt/netbox/current/venv-py3/bin/pip3
  - install
  - dns
  item: dns
  msg: |-
    stdout: Collecting dns
  
    :stderr: The directory '/opt/netbox/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/opt/netbox/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
      Could not find a version that satisfies the requirement dns (from versions: )
    No matching distribution found for dns
```

However:
```sh
root@netbox:~# ll /opt/netbox/.cache
ls: cannot access '/opt/netbox/.cache': No such file or directory
```

Thanks.
