### ISSUE TITLE
Fails to deploy on clean Debian 11

### ISSUE THREAD

**Issue by martino87r** [lae/ansible-role-netbox#159]
Hi, the role fails to deploy on clean Debian 11.7 and Ansible 2.14
```
TASK [lae.netbox : Gather OS specific variables] *************************************************************************************************************************************************************************************
task path: /home/martino/.ansible/roles/lae.netbox/tasks/load_variables.yml:2
fatal: [netbox-dev-local]: FAILED! => {
    "msg": "No file was found when using first_found."
}
```
I'm assuming the failure is related to this issue: https://github.com/ansible/ansible/issues/70772

The postgres role went around by ensuring there were no undefined variables in the matching:

```
...

# Variable configuration.
   - name: Include OS-specific variables (Debian).
     include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"-0
-->  when: ansible_os_family == 'Debian'
...
```

**Comment by lae** [comment]
This role relies on the variables being defined so that we know what packages to install. It's not something we can just skip if the variable is undefined.

Can you run `ansible-playbook` prefixed with `ANSIBLE_STDOUT_CALLBACK=debug` (environment variable) and provide the output from that?

I believe Ansible grabs those variables from `/etc/os-release`, which is owned by the `base-files` package. Is this file/package possibly missing for you? I tested deployment on the latest Debian vagrant box (from a few days ago) and it seems to still function correctly.

**Comment by martino87r** [comment]
The issue is caused by the fact that when ansible evaluates `with_first_found` with an undefined variable it fails hence the bug reference, this was working fine prior to 2.9, the variables are gathered from facts and are there except for one which comes from redhat based systems and is thus `undefined`

I will create a PR if time permits, for now I've solved it like this: 
```
- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_distribution | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Debian'

- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:
  - ansible_os_family == 'RedHat'

- name: Include OS-specific variables (Ubuntu).
  include_vars: "{{ ansible_distribution | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_os_family == 'Ubuntu'
```
