### ISSUE TITLE
 Wrong check between Python 3.7 and 3.8

### ISSUE THREAD

**Issue by MozeBaltyk** [lae/ansible-role-netbox#171]
From Netbox doc: Python 3.8 or later is required for NetBox v3.2 and later releases.
 
I installed and set python3.8 on my RHEL8 server but in the `vars/main.yml` 
```yaml
netbox_python_compat_matrix:
  - { netbox_version_min: '2.8.0', python_needed: '3.6.0' }
  - { netbox_version_min: '3.0.0', python_needed: '3.7.0' }
```

so the code force ansible to use 3.7 even though 3.8 is installed and higher than 3.7...  

```yaml
- name: Switch Ansible's Python interpreter to Python 3
  set_fact:
    ansible_python_interpreter: "{{ netbox_python_binary }}"

- name: Recheck new Python interpreter's version
  setup:
    gather_subset: min
    filter: ansible_python_version

# Can't quite check the effective version of a git installation this early since
# the repo isn't checked out, but most users will be on develop in the first
# place so this dumb check should be good enough.
- name: Ensure Python version installed is compatible with this version of Netbox
  assert:
    that:
      - "ansible_python_version is version(item.python_needed, '>=')"
    msg: >
      NetBox {{ item.netbox_version_min }} requires at least Python {{ item.python_needed }}.
      Please either specify an older NetBox version, upgrade to a newer
      distribution that provides Python at least {{ item.python_needed }}, or
      set netbox_python_binary to an appropriate Python {{ item.python_needed }} binary.
  when:
    - netbox_stable and netbox_stable_version is version(item.netbox_version_min, '>=') or netbox_git
  loop: "{{ netbox_python_compat_matrix }}"
```

This code does not take the actual version installed on host.  

Here the error that I get, you can see that it get the former 3.6.8:
```
<cmdb01> (0, b'\r\n\r\n{"ansible_facts": {"ansible_python_version": "3.6.8"}, "invocation": {"module_args": {"gather_subset": ["min"], "filter": ["ansible_python_version"], "gather_timeout": 10, "fact_path": "/etc/ansible/facts.d"}}}\r\n', b"OpenSSH_8.9p1 Ubuntu-3ubuntu0.4, OpenSSL 3.0.2 15 Mar 2022\r\ndebug1: Reading configuration data /.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 12355\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to cmdb01 closed.\r\n")
<cmdb01> ESTABLISH SSH CONNECTION FOR USER: admin
<cmdb01> SSH: EXEC sshpass -d12 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o 'User="admin"' -o ConnectTimeout=10 -o 'ControlPath=".ansible/cp/be1589c20a"' cmdb01 '/bin/sh -c '"'"'rm -f -r /home/admin/.ansible/tmp/ansible-tmp-1708699225.2757225-16697-80241980294455/ > /dev/null 2>&1 && sleep 0'"'"''
<cmdb01> (0, b'', b"OpenSSH_8.9p1 Ubuntu-3ubuntu0.4, OpenSSL 3.0.2 15 Mar 2022\r\ndebug1: Reading configuration data .ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/.ssh/known_hosts'\r\ndebug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> /.ssh/known_hosts2'\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 12355\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\n")
ok: [cmdb01]

TASK [lae.netbox : Ensure Python version installed is compatible with this version of Netbox] **********************************************************************************************
task path: /.ansible/roles/lae.netbox/tasks/main.yml:21
ok: [cmdb01] => (item={'netbox_version_min': '2.8.0', 'python_needed': '3.6.0'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "netbox_version_min": "2.8.0",
        "python_needed": "3.6.0"
    },
    "msg": "All assertions passed"
}
failed: [cmdb01] (item={'netbox_version_min': '3.0.0', 'python_needed': '3.7.0'}) => {
    "ansible_loop_var": "item",
    "assertion": "ansible_python_version is version(item.python_needed, '>=')",
    "changed": false,
    "evaluated_to": false,
    "item": {
        "netbox_version_min": "3.0.0",
        "python_needed": "3.7.0"
    },
    "msg": "NetBox 3.0.0 requires at least Python 3.7.0. Please either specify an older NetBox version, upgrade to a newer distribution that provides Python at least 3.7.0, or set netbox_python_binary to an appropriate Python 3.7.0 binary.\n"
}
```
