### ISSUE TITLE
Add support for Debian 12

### ISSUE THREAD

**Issue by shakin89** [lae/ansible-role-netbox#183]
I've just created the debian-12.yaml in the vars directory and seems to work.
Please add it to the repo. 

```yaml
_netbox_packages:
  - libxml2-dev
  - libxslt1-dev
  - libffi-dev
  - libjpeg-dev
  - graphviz
  - libpq-dev
  - libssl-dev
_netbox_python_packages:
  - python3.11
  - python3.11-dev
  - python3-venv
  - python3-pip
  - python3-psycopg2  # used by ansible's postgres modules
_netbox_python_binary: /usr/bin/python3
_netbox_ldap_packages:
  - libldap2-dev
  - libsasl2-dev
 ```
