### ISSUE TITLE
Support alternative database socket usage

### ISSUE THREAD

**Issue by tyler-8** [lae/ansible-role-netbox#185]
The role task currently [assume the database socket](https://github.com/lae/ansible-role-netbox/blob/69e575f3359f6b98184337b03b463db27b76e916/tasks/main.yml#L44) (if used) is auth-less and port-less. However in some circumstances (like when using `pgbouncer`), passwords and ports are necessary to define for the socket.

This behavior could be controlled with a simple variable flag, for example: `netbox_database_use_alt_socket: true` to ensure only one type of socket validation task is used.

```yaml
- name: Ensure Postgres database exists (via socket with password/port)
  community.postgresql.postgresql_db:
    name: "{{ netbox_database }}"
    login_user: "{{ netbox_database_user }}"
    login_unix_socket: "{{ netbox_database_socket }}"
    port: "{{ netbox_database_port }}"
    login_password: "{{ netbox_database_password }}"
    maintenance_db: "{{ netbox_database_maintenance }}"
  become: true
  become_user: "{{ netbox_database_user }}"
  when:
    - netbox_database_socket is defined
    - netbox_database_use_alt_socket
    - netbox_database_host is not defined
```
