### ISSUE TITLE
Method for skipping EPEL install step

### ISSUE THREAD

**Issue by tyler-8** [lae/ansible-role-netbox#48]
[This task](https://github.com/lae/ansible-role-netbox/blob/master/tasks/install_packages_yum.yml#L2) should be made optional via a variable or tag. In many enterprise RHEL environments, installing your own repository can be a big no-no, or an EPEL clone for the environment may already exist that isn't going to match the public EPEL package in yum.

For instance:
`netbox_install_epel = false`

```
- name: Install EPEL repository
  yum:
    name: epel-release
    state: installed
  when: netbox_install_epel
```
