### ISSUE TITLE
Dump database if migrations are required

### ISSUE THREAD

**Issue by tyler-8** [lae/ansible-role-netbox#63]
It would be extremely useful to check if any migrations need to be applied before doing them, and if migrations are required then have the option to perform a dump of the database data.

This can be easily accomplished with
`./manage.py showmigrations | grep '\[ \]'`

An empty output is returned if no migrations need to be applied. If migrations _are_ needed, then this task could run:

```
- name: Backup database prior to Netbox upgrade
  postgresql_db:
    name: "{{ netbox_database }}"
    state: dump
    target: "netbox_{{ netbox_database }}_backup.tar.gz"
    target_opts: "-n public"
    login_host: "{{ netbox_database_host }}"
    login_password: "{{ netbox_database_password }}"
    login_user: "{{ netbox_database_user }}"
    port: "{{ netbox_database_port }}"
  run_once: True
```

Main concerns are that the server needs to have `pg_dump` installed (part of the `postgresql` package that this package installs anyway) that matches the major release of the database server. That's why this set of tasks needs to happen after system packages are installed but before the migration step is actually run - landing us right in the middle of this role's workflow.
