### ISSUE TITLE
Add netbox_reports variable for uploading of reports

### ISSUE THREAD

**Issue by tyler-8** [lae/ansible-role-netbox#70]
There's currently functionality to upload scripts to the `SCRIPTS_ROOT` directory. I'd like to be able to do the same thing with reports.

From the readme:

---
```yaml
netbox_scripts: []
```
Scripts to upload for use within NetBox. This should be a list of dictionaries with a src attribute, specifying the local path to the script, and a name attribute, specifying the script/module name. For example:

```yaml
netbox_scripts:
  - src: netbox_scripts/migrate_application.py
    name: migrate_application
```
---
